hugo_deb_pkg_link: https://github.com/gohugoio/hugo/releases/download/v0.152.2/hugo_0.152.2_linux-amd64.deb
hugo_github_token: ""
hugo_repo_url: ""
hugo_repo_branch: ""
hugo_srv_dir: "/var/www/hugo"
hugo_public_dir: "{{ hugo_source_dir }}/public/" ## Needs a trailing slash to indicate the files inside public need to be copied
hugo_source_dir: "/home/{{ ansible_user }}/hugo"
