---
- name: Base Configuration
  hosts: all
  pre_tasks:
    - name: Base Configuration | Install System Packages
      become: true
      ansible.builtin.apt:
        name:
          - bash-completion
          - iputils-ping
          - lsof
          - vim
        state: present
        update-cache: true

  roles:
    - role: node-exporter
